package(default_visibility = ["//visibility:public"])

cc_library(
    name = "threadpool-lib",
    hdrs = [
        ":threadpool.h",
    ],
    deps = [
        "//lock:lock-lib",
        "//CGImysql:CGImysql-lib",
    ],
)
